trigger:
  branches:
    include: 
    - blue-green
    - blue-green-template
  paths:
    exclude:
    - azure-pipelines.yml

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-18.04'

    variables:
      wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
      dotnetSdkVersion: '3.1.300'

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'

    - task: Npm@1
      displayName: 'Run npm install'
      inputs:
        verbose: false

    - script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
      displayName: 'Compile Sass assets'

    - task: gulp@1
      displayName: 'Run gulp tasks'

    - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
      displayName: 'Write build info'
      workingDirectory: $(wwwrootDir)

    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration $(buildConfiguration)'
        projects: '**/*.csproj'
        
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*Test.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop

# - stage: 'Dev_rolling'
#   displayName: 'Deploy to the dev environment'
#   dependsOn: Build
#   jobs:
#   - deployment: deployonprem
#     pool:
#       vmImage: 'ubuntu-18.04'
#     environment: 
#       name: 'on-prem vm'
#       resourceType: 'VirtualMachine'
#       tags: 'api'
#     variables:
#     - group: Release
#     strategy:
#       rolling:
#         maxParallel: 2  #for percentages, mention as x%
#         preDeploy:
#           steps:
#           - download: current
#             artifact: drop
#           - script: echo initialize, cleanup, backup, install certs

#         deploy:
#           steps:
        
#           - task: IISWebAppDeploymentOnMachineGroup@0
#             inputs:
#               WebSiteName: 'Default Web Site'
#               Package: '$(Agent.BuildDirectory)\drop\Release\Tailspin.SpaceGame.Web.zip'
#               TakeAppOfflineFlag: true
#               XmlVariableSubstitution: true

- stage: 'Dev_runonce'
  displayName: 'Deploy to the dev environment'
  dependsOn: Build
  jobs:
  - deployment: deployonprem
    environment: 
      name: 'on-prem vm'
      resourceType: 'VirtualMachine'
      tags: 'api'
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

        
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'Default Web Site'
              Package: '$(Agent.BuildDirectory)\drop\Release\Tailspin.SpaceGame.Web.zip'
              TakeAppOfflineFlag: true
              XmlVariableSubstitution: true

  # - deployment: deployonprem1
  #   pool:
  #     vmImage: 'ubuntu-18.04'
  #   environment: 
  #     name: 'on-prem vm'
  #     resourceType: 'VirtualMachine'
  #     tags: 'api'
  #   variables:
  #   - group: Release
  #   strategy:
  #     runOnce:
  #       deploy:
  #         steps:
  #         - download: current
  #           artifact: drop

        
  #         - task: IISWebAppDeploymentOnMachineGroup@0
  #           inputs:
  #             WebSiteName: 'Space Game'
  #             Package: '$(Agent.BuildDirectory)\drop\Release\Tailspin.SpaceGame.Web.zip'
  #             XmlVariableSubstitution: true